version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p8r9y3l2

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t varts-cicd .
      - docker tag varts-cicd:latest public.ecr.aws/p8r9y3l2/varts-cicd:latest      

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/p8r9y3l2/varts-cicd:latest
      - printf '[{"name":"varts-image","imageUri":"public.ecr.aws/p8r9y3l2/varts-cicd:latest"}]' > imagedefinitions.json

artifacts:
  files: 
    - imagedefinitions.json
